[package]
name = "oci_spec"
version = "0.1.0"
edition = "2018"

[features]
default = []
proptests = ["quickcheck"]
builder = ["derive_builder", "getset"]

[dependencies]
serde = { version = "1.0.127", features = ["derive"] }
anyhow = "1.0.42"
serde_json = "1.0.66"
# Waiting for new caps release, replace git with version on release
caps = { git = "https://github.com/lucab/caps-rs", rev = "cb54844", features = ["serde_support"] }
quickcheck = { version = "1.0.3", optional = true }
derive_builder = { version = "0.10.2", optional = true }
getset = { version = "0.1.1", optional = true }
cfg-if = "1.0.0"

[dev-dependencies]
tempfile = "3.2.0"
